# Generated by Django 3.0.3 on 2020-02-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_redditheadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redditheadline',
            old_name='image',
            new_name='reddit_image',
        ),
        migrations.RenameField(
            model_name='redditheadline',
            old_name='title',
            new_name='reddit_title',
        ),
        migrations.RenameField(
            model_name='redditheadline',
            old_name='url',
            new_name='reddit_url',
        ),
    ]
