# Generated by Django 3.0.3 on 2020-02-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200226_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditheadline',
            name='reddit_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
