# Generated by Django 3.0.3 on 2020-02-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20200226_0555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedditHeadline',
            new_name='RedditHeadlines',
        ),
        migrations.RenameModel(
            old_name='Headline',
            new_name='TwitterHeadlines',
        ),
    ]
