# Generated by Django 3.0.3 on 2020-02-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20200226_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterheadline',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
