# Generated by Django 3.0.3 on 2020-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20200226_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterheadline',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twitterheadline',
            name='tweets',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
