# Generated by Django 3.0.3 on 2020-02-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_auto_20200226_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterheadline',
            old_name='tweets',
            new_name='time',
        ),
    ]
