# Generated by Django 3.0.3 on 2020-02-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_auto_20200226_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditheadline',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='twitterheadline',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
