# Generated by Django 3.0.3 on 2020-02-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_auto_20200226_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditheadline',
            name='reddit_title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='redditheadline',
            name='reddit_url',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
