# Generated by Django 3.0.3 on 2020-02-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_auto_20200226_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditheadline',
            name='reddit_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redditheadline',
            name='reddit_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
