# Generated by Django 3.0.3 on 2020-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_auto_20200226_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeHeadline',
            fields=[
                ('youtube_title', models.CharField(max_length=200)),
                ('youtube_image', models.URLField(blank=True, null=True)),
                ('youtube_url', models.TextField(primary_key=True, serialize=False)),
                ('youtube_tag', models.TextField(blank=True, null=True)),
                ('youtube_time', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
