# Generated by Django 3.0.3 on 2020-02-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_youtubeheadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeheadline',
            name='youtube_image',
        ),
        migrations.RemoveField(
            model_name='youtubeheadline',
            name='youtube_tag',
        ),
        migrations.RemoveField(
            model_name='youtubeheadline',
            name='youtube_time',
        ),
        migrations.AlterField(
            model_name='redditheadline',
            name='reddit_title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubeheadline',
            name='youtube_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
