# Generated by Django 3.0.3 on 2020-02-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_auto_20200226_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeheadline',
            name='youtube_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
