# Generated by Django 3.0.3 on 2020-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_youtubeheadline_youtube_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeheadline',
            name='youtube_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
