# Generated by Django 3.0.3 on 2020-03-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_auto_20200301_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterheadline',
            name='tag',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='twitterheadline',
            name='time',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='twitterheadline',
            name='title',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
