# Generated by Django 3.0.3 on 2020-03-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0024_auto_20200311_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditheadline',
            name='reddit_thumbnailUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
