# Generated by Django 3.0.3 on 2020-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0025_redditheadline_reddit_thumbnailurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeheadline',
            name='youtube_thumbnailUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
