# Generated by Django 3.0.3 on 2020-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0026_youtubeheadline_youtube_thumbnailurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeheadline',
            name='youtube_channel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubeheadline',
            name='youtube_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
