# Generated by Django 3.0.3 on 2020-03-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0027_auto_20200311_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleTrends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trends', models.CharField(max_length=200000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
